/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package main;

import java.awt.Color;
import javax.swing.JOptionPane;

/**
 *
 * @author argue
 */
public class Main extends javax.swing.JFrame {

    ConectorBBDD c;

    /**
     * Creates new form Main
     */
    public Main() {
        initComponents();
        setSize(639, 453);
        this.setLocationRelativeTo(null);
        c = new ConectorBBDD();
        c.getConexion();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelAcceso = new javax.swing.JPanel();
        Salir = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jUser = new javax.swing.JTextField();
        jPassword = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        btnEntrar = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(800, 600));

        jPanelAcceso.setPreferredSize(new java.awt.Dimension(800, 600));
        jPanelAcceso.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Salir.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        Salir.setForeground(new java.awt.Color(255, 255, 255));
        Salir.setText("X");
        Salir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SalirMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                SalirMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                SalirMouseExited(evt);
            }
        });
        jPanelAcceso.add(Salir, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 0, 20, 30));

        jLabel2.setFont(new java.awt.Font("Stencil Std", 0, 18)); // NOI18N
        jLabel2.setText("Usuario:");
        jPanelAcceso.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 174, -1, 30));

        jUser.setBackground(new java.awt.Color(255, 255, 0));
        jPanelAcceso.add(jUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 170, 182, 37));

        jPassword.setBackground(new java.awt.Color(255, 255, 0));
        jPassword.setText("jPasswordField1");
        jPassword.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPasswordMouseClicked(evt);
            }
        });
        jPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordActionPerformed(evt);
            }
        });
        jPanelAcceso.add(jPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 230, 182, 40));

        jLabel1.setFont(new java.awt.Font("Stencil Std", 0, 18)); // NOI18N
        jLabel1.setText("Contraseña:");
        jPanelAcceso.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 234, -1, 30));

        jButton1.setBackground(new java.awt.Color(255, 51, 51));
        jButton1.setFont(new java.awt.Font("Stencil Std", 1, 18)); // NOI18N
        jButton1.setText("Regístrate");
        jButton1.setMaximumSize(new java.awt.Dimension(86, 36));
        jButton1.setMinimumSize(new java.awt.Dimension(86, 36));
        jButton1.setPreferredSize(new java.awt.Dimension(86, 36));
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton1MouseExited(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanelAcceso.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 360, 160, 50));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/background/logo_transparent.png"))); // NOI18N
        jLabel3.setText("jLabel3");
        jPanelAcceso.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 10, 50, 40));

        btnEntrar.setBackground(new java.awt.Color(255, 51, 51));
        btnEntrar.setFont(new java.awt.Font("Stencil Std", 1, 18)); // NOI18N
        btnEntrar.setText("Entra");
        btnEntrar.setMaximumSize(new java.awt.Dimension(86, 36));
        btnEntrar.setMinimumSize(new java.awt.Dimension(86, 36));
        btnEntrar.setPreferredSize(new java.awt.Dimension(86, 36));
        btnEntrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnEntrarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnEntrarMouseExited(evt);
            }
        });
        btnEntrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEntrarActionPerformed(evt);
            }
        });
        jPanelAcceso.add(btnEntrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 360, 160, 50));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/background/fondoMenu.png"))); // NOI18N
        jLabel4.setPreferredSize(new java.awt.Dimension(800, 600));
        jPanelAcceso.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 640, 460));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelAcceso, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 640, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelAcceso, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 460, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEntrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEntrarActionPerformed
        // TODO add your handling code here:
        if (jUser.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Debes introducir un usuario", "Cuidado", 0);
        } else if (jPassword.toString().equals("")) {

            JOptionPane.showMessageDialog(this, "Debes introducir una contraseña", "Cuidado", 0);

        } else {
            c.accesoLogin(this, jPassword, jUser);

        }
    }//GEN-LAST:event_btnEntrarActionPerformed

    private void jPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPasswordActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.dispose();
        Registro registro = new Registro();
        registro.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseEntered
        // TODO add your handling code here:
        jButton1.setBackground(Color.black);
        jButton1.setForeground(Color.white);
    }//GEN-LAST:event_jButton1MouseEntered

    private void jButton1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseExited
        // TODO add your handling code here:
        jButton1.setBackground(new Color(255, 51, 51));
        jButton1.setForeground(Color.white);
    }//GEN-LAST:event_jButton1MouseExited

    private void btnEntrarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEntrarMouseEntered
        // TODO add your handling code here:
        btnEntrar.setBackground(Color.black);
        btnEntrar.setForeground(Color.white);
    }//GEN-LAST:event_btnEntrarMouseEntered

    private void btnEntrarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEntrarMouseExited
        // TODO add your handling code here:
        btnEntrar.setBackground(new Color(255, 51, 51));
        btnEntrar.setForeground(Color.white);
    }//GEN-LAST:event_btnEntrarMouseExited

    private void SalirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SalirMouseClicked
        int ventanaYesNotCancel = (JOptionPane.showConfirmDialog(null, "Quieres salir?", "Salir de JumpWalker", JOptionPane.YES_NO_CANCEL_OPTION, JOptionPane.WARNING_MESSAGE));

        switch (ventanaYesNotCancel) {
            case 0:
                dispose();
                break;
            case 1:

                break;
            case 2:

                break;
            default:
                break;
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_SalirMouseClicked

    private void SalirMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SalirMouseEntered
        Salir.setForeground(Color.black);        // TODO add your handling code here:
    }//GEN-LAST:event_SalirMouseEntered

    private void SalirMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SalirMouseExited
        Salir.setForeground(Color.white);        // TODO add your handling code here:
    }//GEN-LAST:event_SalirMouseExited

    private void jPasswordMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPasswordMouseClicked
    jPassword.setText("");
    }//GEN-LAST:event_jPasswordMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Salir;
    private javax.swing.JButton btnEntrar;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanelAcceso;
    private javax.swing.JPasswordField jPassword;
    private javax.swing.JTextField jUser;
    // End of variables declaration//GEN-END:variables
}
