/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package main;

import java.awt.Color;
import javax.swing.JOptionPane;

/**
 *
 * @author argue
 */
public class Registro extends javax.swing.JFrame {

    ConectorBBDD c;

    /**
     * Creates new form Registro
     */
    public Registro() {
        initComponents();
        this.setLocationRelativeTo(null);
        setSize(639, 453);
        c = new ConectorBBDD();
        c.getConexion();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelAcceso = new javax.swing.JPanel();
        Salir = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jUser = new javax.swing.JTextField();
        jPassword = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();
        btnRegistrar = new javax.swing.JButton();
        btnLogin = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jPasswordR = new javax.swing.JPasswordField();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanelAcceso.setPreferredSize(new java.awt.Dimension(1280, 432));
        jPanelAcceso.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Salir.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        Salir.setForeground(new java.awt.Color(255, 255, 255));
        Salir.setText("X");
        Salir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SalirMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                SalirMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                SalirMouseExited(evt);
            }
        });
        jPanelAcceso.add(Salir, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 0, 20, 30));

        jLabel2.setFont(new java.awt.Font("Stencil Std", 1, 18)); // NOI18N
        jLabel2.setText("Usuario:");
        jPanelAcceso.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 170, -1, 30));

        jUser.setBackground(new java.awt.Color(255, 255, 0));
        jPanelAcceso.add(jUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 170, 249, 30));

        jPassword.setBackground(new java.awt.Color(255, 255, 0));
        jPassword.setText("jPasswordField1");
        jPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordActionPerformed(evt);
            }
        });
        jPanelAcceso.add(jPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 210, 249, 30));

        jLabel1.setFont(new java.awt.Font("Stencil Std", 1, 18)); // NOI18N
        jLabel1.setText("Contraseña:");
        jPanelAcceso.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 210, 110, 30));

        btnRegistrar.setBackground(new java.awt.Color(255, 51, 51));
        btnRegistrar.setFont(new java.awt.Font("Stencil Std", 1, 18)); // NOI18N
        btnRegistrar.setText("Registro");
        btnRegistrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnRegistrarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnRegistrarMouseExited(evt);
            }
        });
        btnRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarActionPerformed(evt);
            }
        });
        jPanelAcceso.add(btnRegistrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 360, 160, 50));

        btnLogin.setBackground(new java.awt.Color(255, 51, 51));
        btnLogin.setFont(new java.awt.Font("Stencil Std", 1, 18)); // NOI18N
        btnLogin.setText("Volver");
        btnLogin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnLoginMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnLoginMouseExited(evt);
            }
        });
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });
        jPanelAcceso.add(btnLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 360, 160, 50));

        jLabel4.setFont(new java.awt.Font("Stencil Std", 1, 18)); // NOI18N
        jLabel4.setText("Repetir Contra:");
        jPanelAcceso.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 250, -1, 30));

        jPasswordR.setBackground(new java.awt.Color(255, 255, 0));
        jPasswordR.setText("jPasswordField1");
        jPasswordR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordRActionPerformed(evt);
            }
        });
        jPanelAcceso.add(jPasswordR, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 250, 249, 30));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/background/fondoMenu.png"))); // NOI18N
        jLabel5.setPreferredSize(new java.awt.Dimension(800, 600));
        jPanelAcceso.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 640, 460));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelAcceso, javax.swing.GroupLayout.DEFAULT_SIZE, 640, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelAcceso, javax.swing.GroupLayout.PREFERRED_SIZE, 453, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPasswordActionPerformed

    private void resetearCampos() {
        jUser.setText("");
        jPassword.setText("");
        jPasswordR.setText("");
    }

    private void btnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarActionPerformed
        // TODO add your handling code here:
        String password = String.valueOf(jPassword.getPassword());
        String password2 = String.valueOf(jPasswordR.getPassword());

        if (jUser.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Debes introducir un usuario", "Error Registro", 0);
        } else if (password.equals("")) {
            JOptionPane.showMessageDialog(this, "Debes introducir una contraseña", "Error Registro", 0);
        } else if (password2.equals("")) {
            resetearCampos();
            JOptionPane.showMessageDialog(this, "Debes introducir de nuevo la contraseña", "Error Registro", 0);
        } else if (!password.equals(password2)) {
            JOptionPane.showMessageDialog(this, "Error las contraseñas no son iguales", "Error Registro", 0);
        } else {
            c.registrarUser(this, jPassword, jUser);
        }
    }//GEN-LAST:event_btnRegistrarActionPerformed

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
        // TODO add your handling code here:
        this.dispose();
        Main main = new Main();
        main.setVisible(true);
    }//GEN-LAST:event_btnLoginActionPerformed

    private void jPasswordRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordRActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPasswordRActionPerformed

    private void btnLoginMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLoginMouseEntered
        // TODO add your handling code here:
        btnLogin.setBackground(Color.black);
        btnLogin.setForeground(Color.white);
    }//GEN-LAST:event_btnLoginMouseEntered

    private void btnLoginMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLoginMouseExited
        // TODO add your handling code here:
        btnLogin.setBackground(new Color(255, 51, 51));
        btnLogin.setForeground(Color.white);
    }//GEN-LAST:event_btnLoginMouseExited

    private void btnRegistrarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRegistrarMouseEntered
        // TODO add your handling code here:
        btnRegistrar.setBackground(Color.black);
        btnRegistrar.setForeground(Color.white);
    }//GEN-LAST:event_btnRegistrarMouseEntered

    private void btnRegistrarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRegistrarMouseExited
        // TODO add your handling code here:
        btnRegistrar.setBackground(new Color(255, 51, 51));
        btnRegistrar.setForeground(Color.white);
    }//GEN-LAST:event_btnRegistrarMouseExited

    private void SalirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SalirMouseClicked
        int ventanaYesNotCancel = (JOptionPane.showConfirmDialog(null, "Quieres salir?", "Salir de JumpWalker", JOptionPane.YES_NO_CANCEL_OPTION, JOptionPane.WARNING_MESSAGE));

        switch (ventanaYesNotCancel) {
            case 0:
                dispose();
                break;
            case 1:

                break;
            case 2:

                break;
            default:
                break;
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_SalirMouseClicked

    private void SalirMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SalirMouseEntered
        Salir.setForeground(Color.black);        // TODO add your handling code here:
    }//GEN-LAST:event_SalirMouseEntered

    private void SalirMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SalirMouseExited
        Salir.setForeground(Color.white);        // TODO add your handling code here:
    }//GEN-LAST:event_SalirMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Registro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Salir;
    private javax.swing.JButton btnLogin;
    private javax.swing.JButton btnRegistrar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanelAcceso;
    private javax.swing.JPasswordField jPassword;
    private javax.swing.JPasswordField jPasswordR;
    private javax.swing.JTextField jUser;
    // End of variables declaration//GEN-END:variables
}
